# Generated by Django 4.2.16 on 2026-07-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type_notif",
            field=models.CharField(
                choices=[
                    ("payment_success", "Paiement réussi"),
                    ("payment_failed", "Paiement échoué"),
                    ("subscription_activated", "Abonnement activé"),
                    ("subscription_expired", "Abonnement expiré"),
                    ("withdrawal_approved", "Retrait approuvé"),
                    ("withdrawal_rejected", "Retrait rejeté"),
                    ("withdrawal_completed", "Retrait complété"),
                    ("new_publication", "Nouvelle publication"),
                    ("new_comment", "Nouveau commentaire"),
                    ("new_reply", "Nouvelle réponse"),
                    ("system", "Système"),
                ],
                default="system",
                max_length=30,
            ),
        ),
    ]
