org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -XX:ReservedCodeCacheSize=128m -Xss256k -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=false
org.gradle.configuration-cache=false
org.gradle.parallel=false
org.gradle.daemon=false
kotlin.code.style=official
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr