org.gradle.jvmargs=-Xmx1280m -XX:MaxMetaspaceSize=320m -XX:ReservedCodeCacheSize=96m -Xss256k -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=false
org.gradle.configuration-cache=false
org.gradle.parallel=false
org.gradle.daemon=false
kotlin.code.style=official
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr