// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0w7K5N6fydcfa6ad2LEyQ0x16_YOQlfo',
    appId: '1:959894274903:web:10d777831007126d143412',
    messagingSenderId: '959894274903',
    projectId: 'digitalpress-ec022',
    authDomain: 'digitalpress-ec022.firebaseapp.com',
    storageBucket: 'digitalpress-ec022.firebasestorage.app',
    measurementId: 'G-XKXMCZ3XGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_13kxVaywrPjlyGFQXZl5h0vuOBofaUc',
    appId: '1:959894274903:android:33d33831976b1a6b143412',
    messagingSenderId: '959894274903',
    projectId: 'digitalpress-ec022',
    storageBucket: 'digitalpress-ec022.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX_mRXq5VKxtJ9yXBe2PwG4c0C6N0qjU0',
    appId: '1:959894274903:ios:b05c8e6e684b2b43143412',
    messagingSenderId: '959894274903',
    projectId: 'digitalpress-ec022',
    storageBucket: 'digitalpress-ec022.firebasestorage.app',
    iosBundleId: 'com.example.digitalpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX_mRXq5VKxtJ9yXBe2PwG4c0C6N0qjU0',
    appId: '1:959894274903:ios:b05c8e6e684b2b43143412',
    messagingSenderId: '959894274903',
    projectId: 'digitalpress-ec022',
    storageBucket: 'digitalpress-ec022.firebasestorage.app',
    iosBundleId: 'com.example.digitalpress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0w7K5N6fydcfa6ad2LEyQ0x16_YOQlfo',
    appId: '1:959894274903:web:a06d520ce828dfb6143412',
    messagingSenderId: '959894274903',
    projectId: 'digitalpress-ec022',
    authDomain: 'digitalpress-ec022.firebaseapp.com',
    storageBucket: 'digitalpress-ec022.firebasestorage.app',
    measurementId: 'G-V9BWWDE16K',
  );
}
