// File generated by FlutterFire CLI.
// ⚠️ CORRECTIF DU 2026-08-14 : le package Android/iOS de l'app est
// désormais "com.digitalpress.app" (voir android/app/build.gradle.kts et
// ios PRODUCT_BUNDLE_IDENTIFIER) — mais ce fichier référence encore
// l'ANCIEN "com.example.digitalpress" tel qu'enregistré dans Firebase.
// Modifier ce fichier à la main NE SUFFIT PAS : les `appId` ci-dessous
// sont liés côté serveur Firebase à l'ancien package. Il faut, côté
// Firebase Console (action humaine, hors de portée du code) :
//   1. Ajouter une nouvelle app Android/iOS avec le package
//      "com.digitalpress.app" au projet Firebase existant (ou renommer
//      l'app existante si Firebase le permet).
//   2. Relancer `flutterfire configure` pour régénérer ce fichier.
//   3. Retélécharger google-services.json / GoogleService-Info.plist.
// Tant que ce n'est pas fait, Firebase (notifications push FCM, etc.)
// continuera de fonctionner avec l'ancien package "com.example.digitalpress"
// — donc PAS avec le build réel de l'app une fois le nouveau package actif.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0w7K5N6fydcfa6ad2LEyQ0x16_YOQlfo',
    appId: '1:959894274903:web:10d777831007126d143412',
    messagingSenderId: '959894274903',
    projectId: 'digitalpress-ec022',
    authDomain: 'digitalpress-ec022.firebaseapp.com',
    storageBucket: 'digitalpress-ec022.firebasestorage.app',
    measurementId: 'G-XKXMCZ3XGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0bEwIRQ4o79cc12zKqkTrBiWxivsklBs',
    appId: '1:601381319647:android:2b551fe57e175bdf5aca6a',
    messagingSenderId: '601381319647',
    projectId: 'digitalpress-ec022-f1cce',
    storageBucket: 'digitalpress-ec022-f1cce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX_mRXq5VKxtJ9yXBe2PwG4c0C6N0qjU0',
    appId: '1:959894274903:ios:b05c8e6e684b2b43143412',
    messagingSenderId: '959894274903',
    projectId: 'digitalpress-ec022',
    storageBucket: 'digitalpress-ec022.firebasestorage.app',
    iosBundleId: 'com.example.digitalpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX_mRXq5VKxtJ9yXBe2PwG4c0C6N0qjU0',
    appId: '1:959894274903:ios:b05c8e6e684b2b43143412',
    messagingSenderId: '959894274903',
    projectId: 'digitalpress-ec022',
    storageBucket: 'digitalpress-ec022.firebasestorage.app',
    iosBundleId: 'com.example.digitalpress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0w7K5N6fydcfa6ad2LEyQ0x16_YOQlfo',
    appId: '1:959894274903:web:a06d520ce828dfb6143412',
    messagingSenderId: '959894274903',
    projectId: 'digitalpress-ec022',
    authDomain: 'digitalpress-ec022.firebaseapp.com',
    storageBucket: 'digitalpress-ec022.firebasestorage.app',
    measurementId: 'G-V9BWWDE16K',
  );
}
