# Generated by Django 4.2.16 on 2026-06-08 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("publications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensuel"),
                            ("quarterly", "Trimestriel"),
                            ("yearly", "Annuel"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "max_publications",
                    models.PositiveIntegerField(default=0, help_text="0 = illimité"),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True, help_text="Fonctionnalités, une par ligne"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Plan d'abonnement",
                "verbose_name_plural": "Plans d'abonnement",
                "ordering": ["prix"],
            },
        ),
        migrations.CreateModel(
            name="Abonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("expired", "Expiré"),
                            ("cancelled", "Annulé"),
                            ("pending", "En attente"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(default=False)),
                ("transaction_ref", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="abonnements.plan",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = abonnement global à la plateforme",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonnements",
                        to="publications.publication",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "publisher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        limit_choices_to={"role": "reader"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonnements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement",
                "verbose_name_plural": "Abonnements",
                "ordering": ["-created_at"],
            },
        ),
    ]
