# Generated by Django 4.2.16 on 2026-07-07 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("abonnements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "publisher"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
