# Generated by Django 4.2.16 on 2026-08-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abonnements", "0009_adjust_max_reader_plans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformplan",
            name="features",
            field=models.TextField(
                blank=True, help_text="Fonctionnalités, une par ligne (texte affiché)"
            ),
        ),
    ]
