# Generated by Django 4.2.16 on 2026-08-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abonnements", "0011_paliers_automatiques_sans_paiement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformplan",
            name="min_publications",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Nombre de publications requis pour atteindre ce palier",
            ),
        ),
        migrations.AlterField(
            model_name="platformplan",
            name="min_sales",
            field=models.PositiveIntegerField(
                default=0, help_text="Nombre de ventes requis pour atteindre ce palier"
            ),
        ),
        migrations.AlterField(
            model_name="platformplan",
            name="min_subscribers",
            field=models.PositiveIntegerField(
                default=0, help_text="Nombre d'abonnés requis pour atteindre ce palier"
            ),
        ),
        migrations.AlterField(
            model_name="platformplan",
            name="prix",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
