# Generated by Django 4.2.16 on 2026-08-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("abonnements", "0012_alter_platformplan_min_publications_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="platformplan",
            options={
                "ordering": ["min_subscribers", "min_publications", "min_sales"],
                "verbose_name": "Plan d'abonnement plateforme",
                "verbose_name_plural": "Plans d'abonnement plateforme",
            },
        ),
    ]
