# Generated by Django 4.2.16 on 2026-07-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="solde",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Solde portefeuille client/lecteur",
                max_digits=12,
            ),
        ),
    ]
