# Generated by Django 4.2.16 on 2026-07-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0003_add_conversations"),
        ("accounts", "0003_posterwarning_passwordresetcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_categories",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="publications.category"
            ),
        ),
    ]
