# Generated by Django 6.0.7 on 2026-07-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_favorite_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="favorite_categories",
        ),
    ]
