# Generated by Django 6.0.7 on 2026-07-30 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_favorite_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="billing_address",
            field=models.TextField(blank=True, help_text="Adresse de facturation"),
        ),
        migrations.AddField(
            model_name="user",
            name="billing_phone",
            field=models.CharField(
                blank=True, help_text="Numéro de facturation / contact", max_length=25
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True, help_text="Activer les notifications email"
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True, help_text="Activer les notifications push (FCM)"
                    ),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(
                        default=False, help_text="Activer les notifications SMS"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immédiat"),
                            ("daily_digest", "Digest quotidien"),
                            ("disabled", "Désactivé"),
                        ],
                        default="immediate",
                        help_text="Fréquence des notifications email",
                        max_length=20,
                    ),
                ),
                ("notify_new_publication", models.BooleanField(default=True)),
                ("notify_payment", models.BooleanField(default=True)),
                ("notify_subscription", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence de notification",
                "verbose_name_plural": "Préférences de notification",
            },
        ),
    ]
