# Generated by Django 4.2.16 on 2026-08-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_publisher_verification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="billing_address",
            field=models.TextField(
                blank=True, default="", help_text="Adresse de facturation"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="billing_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Numéro de facturation / contact",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.DeleteModel(
            name="NotificationPreference",
        ),
    ]
