# Generated by Django 4.2.16 on 2026-08-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0008_alter_user_billing_address_alter_user_billing_phone_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="publisherprofile",
            name="cover_image",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Image de couverture de la page publique du profil éditeur",
            ),
        ),
    ]
