# Generated by Django — activation par email (OTP 15 min, note Dr. Sissoko)
#
# 1. Nouveau modèle EmailVerificationCode (code OTP d'activation de compte).
# 2. Migration de données : tous les comptes EXISTANTS sont marqués
#    is_verified=True. Sans cette étape, la connexion bloquerait
#    rétroactivement tous les utilisateurs déjà inscrits (le login refuse
#    désormais les comptes non vérifiés). Seuls les NOUVEAUX comptes créés
#    par /accounts/register/ démarrent non vérifiés et doivent activer
#    leur compte avec le code reçu par email.
import django.db.models.deletion
from django.db import migrations, models


def mark_existing_users_verified(apps, schema_editor):
    """Marque tous les comptes existants comme vérifiés : ils restent
    connectables sans casser le flux (le login refuse désormais les comptes
    non vérifiés)."""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(is_verified=False).update(is_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_publisherprofile_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_codes', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Code de vérification email',
                'verbose_name_plural': 'Codes de vérification email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(
            mark_existing_users_verified,
            # Rien à annuler : is_verified était False par défaut avant.
            migrations.RunPython.noop,
        ),
    ]
