# Generated by Django 4.2.16 on 2026-07-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0005_reader_categories_favorites"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="video_url",
            field=models.URLField(blank=True),
        ),
    ]
