# Generated by Django 6.0.7 on 2026-07-16 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0003_conversations"),
        ("publications", "0006_publication_video_url"),
    ]

    operations = []
