# Generated by Django 4.2.16 on 2026-07-18 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("publications", "0007_merge_20260716_0111"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="original_publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resold_versions",
                to="publications.publication",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="resell_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prix pour l'achat des droits de revente par un autre média",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CollaborationRight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer_publisher",
                    models.ForeignKey(
                        limit_choices_to={"role": "publisher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_rights_bought",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_rights_sold",
                        to="publications.publication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Droit de collaboration",
                "verbose_name_plural": "Droits de collaboration",
                "unique_together": {("buyer_publisher", "original_publication")},
            },
        ),
    ]
