# Generated by Django 4.2.16 on 2026-08-15 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paiements", "0005_alter_transaction_type_transaction"),
        ("publications", "0010_publication_is_subscriber_exclusive"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration_days", models.PositiveIntegerField(default=7)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de paiement"),
                            ("active", "Active"),
                            ("expired", "Expirée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_promotions",
                        to="publications.publication",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_promotions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="paiements.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mise en avant payante",
                "verbose_name_plural": "Mises en avant payantes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PublicationView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewer_key", models.CharField(max_length=100)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_events",
                        to="publications.publication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vue de publication",
                "verbose_name_plural": "Vues de publications",
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["publication", "viewed_at"],
                        name="publication_publica_a7a442_idx",
                    )
                ],
            },
        ),
    ]
