# Generated by Django 4.2.16 on 2026-07-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paiements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type_transaction",
            field=models.CharField(
                choices=[
                    ("subscription", "Abonnement"),
                    ("purchase", "Achat unitaire"),
                    ("resell_right", "Achat de droit de revente"),
                    ("withdrawal", "Retrait éditeur"),
                    ("commission", "Commission plateforme"),
                    ("refund", "Remboursement"),
                ],
                max_length=20,
            ),
        ),
    ]
