# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paiements", "0003_transaction_publisher_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type_transaction",
            field=models.CharField(
                choices=[
                    ("subscription", "Abonnement"),
                    ("platform_subscription", "Abonnement plateforme (éditeur)"),
                    ("purchase", "Achat unitaire"),
                    ("resell_right", "Achat de droit de revente"),
                    ("withdrawal", "Retrait éditeur"),
                    ("commission", "Commission plateforme"),
                    ("refund", "Remboursement"),
                ],
                max_length=50,
            ),
        ),
    ]
