# Generated by Django 4.2.16 on 2026-06-08 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("publications", "0001_initial"),
        ("paiements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periode_mois", models.PositiveSmallIntegerField()),
                ("periode_annee", models.PositiveSmallIntegerField()),
                (
                    "total_recettes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_commissions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_retraits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_remboursements",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "solde_theorique",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "solde_reel",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "ecart",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("nb_transactions", models.PositiveIntegerField(default=0)),
                ("nb_ecritures", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("reconciled", "Réconcilié"),
                            ("anomalie", "Anomalie détectée"),
                        ],
                        default="en_cours",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Réconciliation comptable",
                "verbose_name_plural": "Réconciliations comptables",
                "ordering": ["-periode_annee", "-periode_mois"],
                "unique_together": {("periode_annee", "periode_mois")},
            },
        ),
        migrations.CreateModel(
            name="EcritureComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                (
                    "date_ecriture",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "type_ecriture",
                    models.CharField(
                        choices=[
                            ("recette", "Recette"),
                            ("depense", "Dépense"),
                            ("commission", "Commission plateforme"),
                            ("retrait", "Retrait éditeur"),
                            ("remboursement", "Remboursement"),
                            ("regularisation", "Régularisation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "compte_debit",
                    models.CharField(
                        choices=[
                            ("411000", "Clients"),
                            ("401000", "Fournisseurs / Éditeurs"),
                            ("706000", "Prestations de services"),
                            ("708000", "Commissions"),
                            ("512000", "Banque / Mobile Money"),
                            ("471000", "Compte d'attente"),
                            ("445800", "TVA collectée"),
                            ("627000", "Frais bancaires"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "compte_credit",
                    models.CharField(
                        choices=[
                            ("411000", "Clients"),
                            ("401000", "Fournisseurs / Éditeurs"),
                            ("706000", "Prestations de services"),
                            ("708000", "Commissions"),
                            ("512000", "Banque / Mobile Money"),
                            ("471000", "Compte d'attente"),
                            ("445800", "TVA collectée"),
                            ("627000", "Frais bancaires"),
                        ],
                        max_length=20,
                    ),
                ),
                ("libelle", models.CharField(max_length=500)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "montant_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("devise", models.CharField(default="FCFA", max_length=10)),
                ("periode_mois", models.PositiveSmallIntegerField()),
                ("periode_annee", models.PositiveSmallIntegerField()),
                ("is_reconciled", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecritures_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editeur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecritures_editeur",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecritures",
                        to="publications.publication",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecriture",
                        to="paiements.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Écriture comptable",
                "verbose_name_plural": "Écritures comptables",
                "ordering": ["-date_ecriture"],
                "indexes": [
                    models.Index(
                        fields=["periode_annee", "periode_mois"],
                        name="comptabilit_periode_1a0d2d_idx",
                    ),
                    models.Index(
                        fields=["editeur"], name="comptabilit_editeur_b330f3_idx"
                    ),
                    models.Index(
                        fields=["type_ecriture"], name="comptabilit_type_ec_d72cc4_idx"
                    ),
                    models.Index(
                        fields=["is_reconciled"], name="comptabilit_is_reco_d13dda_idx"
                    ),
                ],
            },
        ),
    ]
