# Generated by Django 4.2.16 on 2026-07-08 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures', to='paiements.transaction'),
        ),
    ]
